version: '3.8'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  cron:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ms=stock_generator
    depends_on:
      - database
    environment:
      - DB_LINK=postgresql://postgres:12345678@database/postgres

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ms=realtime-stock-prices-api
    depends_on:
      - database
    environment:
      - DB_LINK=postgresql://postgres:12345678@database/postgres

  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - 8080:8080
